### PR TITLE
Reorganization, attributes, and added support for multiple drush installs

### PR DESCRIPTION
**Pull request by patcon**
Mhen. Wanted to use the cookbook to build out our chef roles to mimic acquia's setup. Seemed to make sense.

### CODE REVIEW

**Comment by msonnabaum** [comment]
Not sure how I missed this before. Can you get it to reapply again and I'll review it?

**Comment by patcon** [comment]
No worries, and yep sure thing. I'll make a new clean branch and tag it later. thanks man

**Comment by dkingofpa** [comment]
@msonnabaum @patcon  Is anything going on with this pull request?

**Comment by patcon** [comment]
I'm not sure whether it still makes sense after we moved to using an install_method attr... It would only ever work for the git install_method. I'm down with rerolling. Sprint day tomorrow, so I'm going to try to give this cookbook some attention :)

Thanks for the bump man

**Comment by mparker17** [comment]
As far as I can see, the only thing this PR does that `master` doesn't do now is set up bash completion.

Would it make sense to close this and file a follow-up feature request to add bash completion?

**Comment by patcon** [comment]
Makes sense! I'm down with that. :+1:

**Pull request closed without merging**
