### PR TITLE
Execute provider implementation

### PR DESCRIPTION
**Pull request by ksorokin**

### CODE REVIEW

**Comment by patcon** [comment]
Any other impartial parties want to give a +1 on this?

cc: @mparker17

**Comment by mparker17** [comment]
I'll need to test this to see if it still works (4 months is a long time!); but I like the idea very much!

Aside: I'm not totally impartial... [I was working on my own implementation of an LWRP](https://github.com/malldatabase/chef-drush/tree/feature-lwrp). However, I'm happy to build on other people's work!

**Comment by patcon** [comment]
Rockin. Let me know and I'm happy to merge in

**Comment by mparker17** [comment]
I've confirmed that this works... I'd say it's good to merge!

---

I added...

```
drush_execute "dl" do
    cwd "/home/vagrant"
    options %W{coder --dev}
end
```

... to another recipe in the runlist, and sure enough, the development version of the coder module was downloaded.

**Comment by patcon** [comment]
Coolio! :+1:

**Comment by patcon** [comment]
OK cool, merged. Was thinking about this, and tbh, not sure I see this as a pattern to encourage... Usually resources help abstract things away in a helpful way, but not sure if this is helpful. As in, it makes things look "chef-like" rather than like a shell command, but I'm not sure what it makes better.

Anyhow, would appreciate feedback on that if anyone has any thoughts :)

**Comment by mparker17** [comment]
I think that, as part of provisioning a machine, someone might want to install Drush, run Drush commands (and `ignore_failure` or retry after a bit), perform actions `only_if` or `not_if` a Drush command succeeds, be notified if a Drush command runs, etc.

A lot of this functionality comes for free with lightweight resource providers (LWRPs); and other cookbooks like MySQL, PHP, etc. provide this functionality; and some of the attributes, guards and notifications are hard or impossible to do by running a drush command in a `bash` resource.

As it turns out, this is exactly my use case, and I was going to add this functionality to a fork if nobody else was :stuck_out_tongue:

**Comment by patcon** [comment]
I'm still no convinced it's a worthwhile practice -- you can use an `execute` resource and add lots of chef dsl goodness around it, without obfuscating the drush command being run -- but to each their own :)

**Pull request merged**
