### PR TITLE
Added drush_make recipe

### PR DESCRIPTION
**Pull request by patcon**
Oh hey, forgot to send this through.

### CODE REVIEW

**Comment by msonnabaum** [comment]
I'm happy to take this while we don't yet have a drush LWRP to handle extensions, but I'm not sure about a couple things.

First, I don't see the point in linking it. Why not download straight to the commands dir? I could also see something like this, which would be sort of a half-assed LWRP:

``` ruby
  bash "install-drush-make" do
    code <<-EOH
    (drush dl drush_make)
    EOH
    not_if "drush | grep make"
  end
```

Drush is smart enough to put extensions where they need to go, so I'd rather use it than introduce our own logic.

**Comment by patcon** [comment]
I'm all for using drush where it makes sense. Haven't used enough extensions to know whether drush knows all the modules that have abnormal installs like this, but if it works, why not.

And yep, linking isn't necessary. Just partial to the idea of being able to replace drush to upgrade without removing extensions, but I guess that's not an issue with chef-client managing things.

**Comment by patcon** [comment]
Only tangentially related, but install_path on extensions should be an attribute (or a parameter attribute in the case of a resource). Was just speaking with @darkoantic on the way home, and he brought up a good point -- with vagrant, you can run drush not just from within the VM, but from your host if the drupal root is shared.

So if you install an extension in a system dir on the VM, devs won't be able to just boot the vagrant instance and start rocking from their host machine. (They'll lack the extension even if they have drush.) Same goes for site aliases.

So for smooth workflow, it's likely we'll want to leave the option to place these files somewhere else (in the shared dir, in this case).

**Comment by msonnabaum** [comment]
So it sounds like you want to have chef attributes that would write out to a drushrc.php.

drushrc.php.erb sounds pretty gross, but justified in this case :)

**Comment by glennpratt** [comment]
@patcon Might be easier to just put the entire Drush directory in a shared folder.

Configuring the host to use things provided different guests is a big issue, even beyond the scope of this.

I'm working on an LWRP for installing projects with drush.  If anyone knows off the top, how do I:
- Install a project globally with drush (ie drush_make, in commands dir for all users).
- List or stat projects providing drush commands by name (ie drush_make again).

This maybe obvious, I haven't tried yet.

**Comment by msonnabaum** [comment]
The first is easy, just drush dl it. Let drush figure out where it needs to go. If there isn't a .module dir we default to either share or ~/.drush depending on what we can write to.

Listing is more difficult. I gave the LWRP a shot recently and I ran into that issue quickly, which prompted this: http://drupal.org/node/1210306.

It wouldn't be hard to write such a command, it just hasn't been done yet.

**Comment by patcon** [comment]
@glennpratt this seems like it could involve many complicated things (for instance, iterate through the users databag if using chef-server), but I think the simplest would involve having a default attribute for install_dir of drush:

chef-repo/cookbooks/drush/attributes/default.rb
`default[:drush][:install_dir] = /usr/share/drush`

and an install_dir resource attribute in the LWRP:

readme

``` ruby
drush_extension "drush_make" do
  install_dir "/usr/share/drush/commands"
  version "6.x-2.2"
end
```

and so if we need it in multiple user's home dirs:

chef-repo/site-cookbooks/mysite/attrbitues/default.rb
`normal[:drush][:install][:install_dir] = [ "/home/user1/.drush", "/home/user2/.drush" ]`

readme

``` ruby
drush_extension "drush_make" do
  install_dir [ "/home/user1/.drush/commands", "/home/user2/.drush/commands" ]
  version "6.x-2.2"
end
```

Did I understand correctly?

EDIT: Hm. Seems I misunderstood the question as chef-centric :) don't mind me

**Pull request merged**
